run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: '1.23'

linters:
  enable:
    # Essential linters
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused          # Replaces: deadcode, structcheck, varcheck
    - gosimple
    - ineffassign
    - typecheck

    # Code quality
    - goconst
    - gocyclo
    - goimports
    - misspell
    - unparam
    - unconvert
    - dupl
    - gocritic
    - gochecknoinits
    - whitespace
    - revive

    # Security
    - gosec

    # Modern replacements for deprecated linters
    - copyloopvar     # Replaces: exportloopref (for Go 1.22+)

  disable:
    # Deprecated linters (removed)
    # - deadcode (replaced by unused)
    # - structcheck (replaced by unused)
    # - varcheck (replaced by unused)
    # - exportloopref (replaced by copyloopvar)
    # - exhaustivestruct (deprecated)
    # - gomnd (deprecated)

    # Style linters (can be enabled later)
    - exhaustive
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - lll
    - nlreturn
    - testpackage
    - wsl
    - mnd              # Replacement for gomnd, but disabled for now

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G404  # Use of weak random number generator (okay for non-security purposes)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

# Use the modern output format
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
